package com.drpicox.game.december;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc
public class Post_20221206_LotsOfNewCards_Test {

    @Autowired Post_20221206_LotsOfNewCards_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-12-06_lots_of_new_cards", "a410f4a08fb46fe4debf7cbf2398a5be");
        context.beforeTest();

        // # Lots of new cards                                         // # Lots of new cards

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Demon      | Critter  |         3 |                   // ### | Demon      | Critter  |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Demon");                      // * Given there are 1 "Demon" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Demon", 3, "Critter");      // * The "Demon" card should have 3 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Harpy      | Critter  |         2 |                   // ### | Harpy      | Critter  |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Harpy");                      // * Given there are 1 "Harpy" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Harpy", 2, "Critter");      // * The "Harpy" card should have 2 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Skeletton  | Critter  |         1 |                   // ### | Skeletton  | Critter  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Skeletton");                  // * Given there are 1 "Skeletton" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Skeletton", 1, "Critter");  // * The "Skeletton" card should have 1 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Skull      | Critter  |         1 |                   // ### | Skull      | Critter  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Skull");                      // * Given there are 1 "Skull" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Skull", 1, "Critter");      // * The "Skull" card should have 1 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Ghost      | Critter  |         1 |                   // ### | Ghost      | Critter  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Ghost");                      // * Given there are 1 "Ghost" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Ghost", 1, "Critter");      // * The "Ghost" card should have 1 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Hungry     | Critter  |         1 |                   // ### | Hungry     | Critter  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Hungry");                     // * Given there are 1 "Hungry" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Hungry", 1, "Critter");     // * The "Hungry" card should have 1 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Monster    | Critter  |         1 |                   // ### | Monster    | Critter  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Monster");                    // * Given there are 1 "Monster" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Monster", 1, "Critter");    // * The "Monster" card should have 1 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Strawman   | Critter  |         1 |                   // ### | Strawman   | Critter  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Strawman");                   // * Given there are 1 "Strawman" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Strawman", 1, "Critter");   // * The "Strawman" card should have 1 in "Critter" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Planet     | Space    |         3 |                   // ### | Planet     | Space    |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Planet");                     // * Given there are 1 "Planet" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Planet", 3, "Space");       // * The "Planet" card should have 3 in "Space" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Darkhelmet | Space    |         2 |                   // ### | Darkhelmet | Space    |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Darkhelmet");                 // * Given there are 1 "Darkhelmet" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Darkhelmet", 2, "Space");   // * The "Darkhelmet" card should have 2 in "Space" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Alien      | Space    |         1 |                   // ### | Alien      | Space    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Alien");                      // * Given there are 1 "Alien" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Alien", 1, "Space");        // * The "Alien" card should have 1 in "Space" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Starbuck   | Space    |         1 |                   // ### | Starbuck   | Space    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Starbuck");                   // * Given there are 1 "Starbuck" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Starbuck", 1, "Space");     // * The "Starbuck" card should have 1 in "Space" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Apollo     | Hero     |         3 |                   // ### | Apollo     | Hero     |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Apollo");                     // * Given there are 1 "Apollo" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Apollo", 3, "Hero");        // * The "Apollo" card should have 3 in "Hero" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Aquaman    | Hero     |         1 |                   // ### | Aquaman    | Hero     |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Aquaman");                    // * Given there are 1 "Aquaman" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Aquaman", 1, "Hero");       // * The "Aquaman" card should have 1 in "Hero" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Bob        | Job      |         3 |                   // ### | Bob        | Job      |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Bob");                        // * Given there are 1 "Bob" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Bob", 3, "Job");            // * The "Bob" card should have 3 in "Job" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Handyman   | Job      |         2 |                   // ### | Handyman   | Job      |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Handyman");                   // * Given there are 1 "Handyman" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Handyman", 2, "Job");       // * The "Handyman" card should have 2 in "Job" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Baker      | Job      |         1 |                   // ### | Baker      | Job      |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Baker");                      // * Given there are 1 "Baker" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Baker", 1, "Job");          // * The "Baker" card should have 1 in "Job" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Blacksmith | Job      |         1 |                   // ### | Blacksmith | Job      |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Blacksmith");                 // * Given there are 1 "Blacksmith" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Blacksmith", 1, "Job");     // * The "Blacksmith" card should have 1 in "Job" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Farmer     | Job      |         1 |                   // ### | Farmer     | Job      |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Farmer");                     // * Given there are 1 "Farmer" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Farmer", 1, "Job");         // * The "Farmer" card should have 1 in "Job" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Bird       | Aviar    |         3 |                   // ### | Bird       | Aviar    |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Bird");                       // * Given there are 1 "Bird" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Bird", 3, "Aviar");         // * The "Bird" card should have 3 in "Aviar" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Nest       | Aviar    |         2 |                   // ### | Nest       | Aviar    |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Nest");                       // * Given there are 1 "Nest" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Nest", 2, "Aviar");         // * The "Nest" card should have 2 in "Aviar" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Egg        | Aviar    |         1 |                   // ### | Egg        | Aviar    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Egg");                        // * Given there are 1 "Egg" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Egg", 1, "Aviar");          // * The "Egg" card should have 1 in "Aviar" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Cow        | Farm     |         3 |                   // ### | Cow        | Farm     |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Cow");                        // * Given there are 1 "Cow" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Cow", 3, "Farm");           // * The "Cow" card should have 3 in "Farm" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Pig        | Farm     |         2 |                   // ### | Pig        | Farm     |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Pig");                        // * Given there are 1 "Pig" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Pig", 2, "Farm");           // * The "Pig" card should have 2 in "Farm" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Sheep      | Farm     |         1 |                   // ### | Sheep      | Farm     |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Sheep");                      // * Given there are 1 "Sheep" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Sheep", 1, "Farm");         // * The "Sheep" card should have 1 in "Farm" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Dog        | Farm     |         1 |                   // ### | Dog        | Farm     |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Dog");                        // * Given there are 1 "Dog" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Dog", 1, "Farm");           // * The "Dog" card should have 1 in "Farm" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Frog       | Farm     |         1 |                   // ### | Frog       | Farm     |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Frog");                       // * Given there are 1 "Frog" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Frog", 1, "Farm");          // * The "Frog" card should have 1 in "Farm" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Buildings  | Building |         3 |                   // ### | Buildings  | Building |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Buildings");                  // * Given there are 1 "Buildings" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Buildings", 3, "Building"); // * The "Buildings" card should have 3 in "Building" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Tower      | Building |         2 |                   // ### | Tower      | Building |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Tower");                      // * Given there are 1 "Tower" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Tower", 2, "Building");     // * The "Tower" card should have 2 in "Building" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Barn       | Building |         1 |                   // ### | Barn       | Building |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Barn");                       // * Given there are 1 "Barn" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Barn", 1, "Building");      // * The "Barn" card should have 1 in "Building" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Cake       | Dish     |         3 |                   // ### | Cake       | Dish     |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Cake");                       // * Given there are 1 "Cake" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Cake", 3, "Dish");          // * The "Cake" card should have 3 in "Dish" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Salad      | Dish     |         1 |                   // ### | Salad      | Dish     |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Salad");                      // * Given there are 1 "Salad" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Salad", 1, "Dish");         // * The "Salad" card should have 1 in "Dish" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Chest      | Treasure |         3 |                   // ### | Chest      | Treasure |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Chest");                      // * Given there are 1 "Chest" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Chest", 3, "Treasure");     // * The "Chest" card should have 3 in "Treasure" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Crystals   | Treasure |         2 |                   // ### | Crystals   | Treasure |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Crystals");                   // * Given there are 1 "Crystals" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Crystals", 2, "Treasure");  // * The "Crystals" card should have 2 in "Treasure" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Gems       | Treasure |         1 |                   // ### | Gems       | Treasure |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Gems");                       // * Given there are 1 "Gems" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Gems", 1, "Treasure");      // * The "Gems" card should have 1 in "Treasure" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Gem        | Treasure |         1 |                   // ### | Gem        | Treasure |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Gem");                        // * Given there are 1 "Gem" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Gem", 1, "Treasure");       // * The "Gem" card should have 1 in "Treasure" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Mage       | Magic    |         3 |                   // ### | Mage       | Magic    |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Mage");                       // * Given there are 1 "Mage" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Mage", 3, "Magic");         // * The "Mage" card should have 3 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Fairy      | Magic    |         2 |                   // ### | Fairy      | Magic    |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Fairy");                      // * Given there are 1 "Fairy" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Fairy", 2, "Magic");        // * The "Fairy" card should have 2 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Dwarf      | Magic    |         1 |                   // ### | Dwarf      | Magic    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Dwarf");                      // * Given there are 1 "Dwarf" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Dwarf", 1, "Magic");        // * The "Dwarf" card should have 1 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Unicorn    | Magic    |         1 |                   // ### | Unicorn    | Magic    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Unicorn");                    // * Given there are 1 "Unicorn" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Unicorn", 1, "Magic");      // * The "Unicorn" card should have 1 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Multicorn  | Magic    |         1 |                   // ### | Multicorn  | Magic    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Multicorn");                  // * Given there are 1 "Multicorn" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Multicorn", 1, "Magic");    // * The "Multicorn" card should have 1 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Dino       | Magic    |         1 |                   // ### | Dino       | Magic    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Dino");                       // * Given there are 1 "Dino" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Dino", 1, "Magic");         // * The "Dino" card should have 1 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Furby      | Magic    |         1 |                   // ### | Furby      | Magic    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Furby");                      // * Given there are 1 "Furby" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Furby", 1, "Magic");        // * The "Furby" card should have 1 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Visitor    | Magic    |         1 |                   // ### | Visitor    | Magic    |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Visitor");                    // * Given there are 1 "Visitor" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Visitor", 1, "Magic");      // * The "Visitor" card should have 1 in "Magic" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Tree       | Vegetal  |         3 |                   // ### | Tree       | Vegetal  |         3 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Tree");                       // * Given there are 1 "Tree" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Tree", 3, "Vegetal");       // * The "Tree" card should have 3 in "Vegetal" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Plants     | Vegetal  |         2 |                   // ### | Plants     | Vegetal  |         2 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Plants");                     // * Given there are 1 "Plants" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Plants", 2, "Vegetal");     // * The "Plants" card should have 2 in "Vegetal" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Plant      | Vegetal  |         1 |                   // ### | Plant      | Vegetal  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Plant");                      // * Given there are 1 "Plant" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Plant", 1, "Vegetal");      // * The "Plant" card should have 1 in "Vegetal" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Flower     | Vegetal  |         1 |                   // ### | Flower     | Vegetal  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Flower");                     // * Given there are 1 "Flower" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Flower", 1, "Vegetal");     // * The "Flower" card should have 1 in "Vegetal" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Flowers    | Vegetal  |         1 |                   // ### | Flowers    | Vegetal  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Flowers");                    // * Given there are 1 "Flowers" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Flowers", 1, "Vegetal");    // * The "Flowers" card should have 1 in "Vegetal" tag.

        // ## New cards                                                // ## New cards
        // ### | $CardName  | $CardTag | $TagValue |                   // ### | $CardName  | $CardTag | $TagValue |
        // ### |------------|----------|----------:|                   // ### |------------|----------|----------:|
        // ### | Coconut    | Vegetal  |         1 |                   // ### | Coconut    | Vegetal  |         1 |
        context.givenANewExample();                                    // * Given a new example.
        context.givenThereAreNSCards(1, "Coconut");                    // * Given there are 1 "Coconut" cards.
        context.reloadTheGame();                                       // * Reload the game.
        context.theSCardShouldHaveNInSTag("Coconut", 1, "Vegetal");    // * The "Coconut" card should have 1 in "Vegetal" tag.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
