package com.drpicox.game;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

import com.drpicox.game.fixtures.Fixtures;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@SpringBootTest
@AutoConfigureMockMvc
public class Post_20220719_VillagersEatFood_Test {

    @Autowired Post_20220719_VillagersEatFood_Context context;
    @Autowired Fixtures fixtures;

    @Test public void testPost() throws Throwable {
        fixtures.runBeforeTestStarts("2022-07-19_villagers_eat_food", "b1f3fa0c802d0863316fec78f95d264e");
        context.beforeTest();

        // # Villagers Eat Food
        // ## Berries are food
        context.givenWeHaveEnteredIntoANewGame();
        context.theSCardShouldHaveNInSTag("Berry", 1, "food");
        context.theSCardShouldHaveNInSTag("Villager", 1, "eats");
        // ## Moons
        context.endTheCurrentMoon();
        context.thereShouldBeNCards(2);
        context.thereShouldBeNoSCard("Berry");
        context.thereShouldBeNSCard(1, "Villager");
        context.thereShouldBeNSCard(1, "Bush");
        // ## Starving
        context.endTheCurrentMoon();
        context.thereShouldBeNCards(2);
        context.thereShouldBeNoSCard("Berry");
        context.thereShouldBeNoSCard("Villager");
        context.thereShouldBeNSCard(1, "Bush");
        context.thereShouldBeNSCard(1, "Corpse");

        context.afterTest();
        fixtures.runWhenTestSuccessful();
    }

}
