package com.drpicox.game;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

import com.drpicox.game.util.TestUtils;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@SpringBootTest
@AutoConfigureMockMvc
public class Post_20220717_BushesVillagersAndBerries_Test {

    @Autowired Post_20220717_BushesVillagersAndBerries_Context context;
    @Autowired TestUtils testUtils;

    @Test public void testPost() throws Throwable {
        testUtils.runBeforeTestStarts("2022-07-17_bushes_villagers_and_berries", "824e6953105ab2951a266edb4038af73");
        context.beforeTest();

        // # Bushes, Villagers and Berries            // # Bushes, Villagers and Berries

        // ## The game                                // ## The game
        context.enterTheGame();                       // * Enter the game.
        context.thereShouldBeNSCard(1, "Villager");   // * There should be 1 "Villager" card.
        context.thereShouldBeNSCard(1, "Berry Bush"); // * There should be 1 "Berry Bush" card.
        context.andThereShouldBeNSCard(1, "Berry");   // * And there should be 1 "Berry" card.

        context.afterTest();
        testUtils.runWhenTestSuccessful();
    }

}
