package com.drpicox.game;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

import com.drpicox.game.fixtures.Fixtures;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@SpringBootTest
@AutoConfigureMockMvc
public class Post_20220721_MoreDetailsAboutHowVillagersEatFood_Test {

    @Autowired Post_20220721_MoreDetailsAboutHowVillagersEatFood_Context context;
    @Autowired Fixtures fixtures;

    @Test public void testPost() throws Throwable {
        fixtures.runBeforeTestStarts("2022-07-21_more_details_about_how_villagers_eat_food", "53d02ab61b4bab6354d458c3c6e9d3d0");
        context.beforeTest();

        // # More Details About How Villagers Eat Food
        // ## More kinds of villagers
        context.givenThereAreNSNSAndNSCards(2, "Villager", 2, "Militia", 2, "Trader");
        context.theSCardShouldHaveNInSTag("Villager", 1, "eats");
        context.theSCardShouldHaveNInSTag("Militia", 2, "eats");
        context.theSCardShouldHaveNInSTag("Trader", 3, "eats");
        context.theSumOfAllSTagsValueShouldBeN("eats", 12);
        // ## More kinds of food
        context.givenThereAreNSNSAndNSCards(2, "Berry", 2, "Apple", 2, "Fruit salad");
        context.theSCardShouldHaveNInSTag("Berry", 1, "food");
        context.theSCardShouldHaveNInSTag("Apple", 2, "food");
        context.theSCardShouldHaveNInSTag("Fruit salad", 3, "food");
        context.theSumOfAllSTagsValueShouldBeN("food", 12);
        // ## Eating
        context.endTheCurrentMoon();
        context.theSumOfAllSTagsValueShouldBeN("eats", 12);
        context.theSumOfAllSTagsValueShouldBeN("food", 0);
        // ## Too much food
        context.givenThereAreNSNSAndNSCards(2, "Berry", 2, "Apple", 3, "Fruit salad");
        context.theSumOfAllSTagsValueShouldBeN("eats", 12);
        context.theSumOfAllSTagsValueShouldBeN("food", 15);
        context.endTheCurrentMoon();
        context.theSumOfAllSTagsValueShouldBeN("eats", 12);
        context.theSumOfAllSTagsValueShouldBeN("food", 2);
        context.thereShouldBeNSCards(2, "Berry");
        context.thereShouldBeNSCards(0, "Apple");
        // ## Too few food
        context.givenThereAreNSNSAndNSCards(3, "Berry", 0, "Apple", 0, "Fruit salad");
        context.theSumOfAllSTagsValueShouldBeN("eats", 12);
        context.theSumOfAllSTagsValueShouldBeN("food", 3);
        context.endTheCurrentMoon();
        context.theSumOfAllSTagsValueShouldBeN("eats", 2);
        context.theSumOfAllSTagsValueShouldBeN("food", 1);
        context.thereShouldBeNSCards(1, "Berry");
        context.thereShouldBeNSCards(2, "Villager");
        context.thereShouldBeNSCards(0, "Militia");
        context.thereShouldBeNSCards(0, "Trader");

        context.afterTest();
        fixtures.runWhenTestSuccessful();
    }

}
