package com.drpicox.game;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

import com.drpicox.game.fixtures.Fixtures;

// !!! IMPORTANT !!!
// This test file is AUTOGENERATED by yarn create-tests
// If you need to update it, run yarn create-tests
// DO NOT MODIFY manually. Keep running yarn create-tests instead,
// while editing your posts.

@SpringBootTest
@AutoConfigureMockMvc
public class Post_20220717_BushesVillagersAndBerries_Test {

    @Autowired Post_20220717_BushesVillagersAndBerries_Context context;
    @Autowired Fixtures fixtures;

    @Test public void testPost() throws Throwable {
        fixtures.runBeforeTestStarts("2022-07-17_bushes_villagers_and_berries", "51a055bba4d9d93d0710867d370c9766");
        context.beforeTest();

        // # Bushes, Villagers and Berries            // # Bushes, Villagers and Berries

        // ## The game                                // ## The game
        context.enterInTheGame();                     // * Enter in the game.
        context.thereShouldBeNCards(3);               // * There should be 3 cards.
        context.thereShouldBeNSCard(1, "Villager");   // * There should be 1 "Villager" card.
        context.thereShouldBeNSCard(1, "Berry Bush"); // * There should be 1 "Berry Bush" card.
        context.andThereShouldBeNSCard(1, "Berry");   // * And there should be 1 "Berry" card.

        context.afterTest();
        fixtures.runWhenTestSuccessful();
    }

}
